import Block from "@/components/Block";
import Container from "@/components/Container";
import Navbar from "@/components/navigation/Navbar";
import Hero from "@/components/sections/Hero";
import WithPower from "@/components/sections/WithPower";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Navbar />
          <Block>
            <Hero />
          </Block>
          <Block>
            <WithPower />
          </Block>
        </Container>
      </main>
    </>
  );
}
